### ISSUE TITLE
Crash. Betteranimalsplus / Whisperwoods.

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/PotatoRunner#2]
potatorunner: beta-1.4.1

architectury: 1.32.68
betteranimalsplus: 11.0.10
whisperwoods: 2.1.1
均为 cf 上 1.16.5 的最后一个版本。

[debug.log](https://github.com/MCTeamPotato/PotatoRunner/files/11627988/debug.log)
[latest.log](https://github.com/MCTeamPotato/PotatoRunner/files/11627989/latest.log)

很好复现。

**Comment by Kasualix** [comment]
看来一个个都是夜猫子，喜欢半夜报bug（
