### ISSUE TITLE
'mixin.stream.entity.villager.entity' related crash.

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/PotatoRunner#3]
[debug.log](https://github.com/MCTeamPotato/PotatoRunner/files/11645913/debug.log)
[latest.log](https://github.com/MCTeamPotato/PotatoRunner/files/11645914/latest.log)

1.4.1-beta

mixin.stream.entity.villager.entity=false 可以解决
我先偷个懒（如果信息不够的话，我会去找是与哪个 mod 冲突

**Comment by Kasualix** [comment]
够了，这个很好修

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/PotatoRunner/releases/tag/1.5.0
